apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: hackaton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              value: zabbix
            - name: ZBX_SERVER_HOST
              value: zabbix-server
            - name: PHP_TZ
              value: America/Sao_Paulo