apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-prometheus
  namespace: hackaton
  labels:
    app: prometheus
    component: tools
  annotations:
    description: "Used to collect metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        component: tools
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - '--config.file=/etc/prometheus/prometheus.yml'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
      volumes:
        - name: prometheus-config
          configMap:
            name: config-prometheus
