apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sqlserver
  namespace: hackaton
  labels:
    app: sqlserver
    component: tools
  annotations:
    description: "Used as database"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
        component: tools
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-credentials
                  key: sqlserver-sa-password
            - name: ACCEPT_EULA
              value: "Y"
          volumeMounts:
            - name: sqlserver-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: pvc-sqlserver
