apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: hackaton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:alpine-latest
          env:
            - name: DB_SERVER_HOST
              value: zabbix-postgres
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              value: zabbix
