apiVersion: v1
kind: Service
metadata:
  name: svc-sqlserver
  namespace: hackaton
  labels:
    app: sqlserver
    component: tools
  annotations:
    description: "Used as database"
spec:
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
  type: ClusterIP
