apiVersion: v1
kind: Service
metadata:
  name: svc-grafana
  namespace: hackaton
  labels:
    app: grafana
    component: tools
  annotations:
    description: "Used to see metrics"
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
