apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: hackaton
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30805
  selector:
    app: zabbix-web
