apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus
  namespace: hackaton
  labels:
    app: prometheus
    component: tools
  annotations:
    description: "Used to collect metrics"
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
