apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-orderapi
  namespace: hackaton
  labels:
    app: orderapi
    component: app
  annotations:
    description: "API to receive write operations"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapi
  template:
    metadata:
      labels:
        app: orderapi
        component: app
    spec:
      containers:
        - name: orderapi
          image: local_orderapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config-rabbitmq
            - configMapRef:
                name: config-sqlserver
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
