apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-orderservice
  namespace: hackaton
  labels:
    app: orderservice
    component: app
  annotations:
    description: "Worker to Write Data"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
        component: app
    spec:
      containers:
        - name: orderservice
          image: local_orderservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
          envFrom:
            - configMapRef:
                name: config-rabbitmq
            - configMapRef:
                name: config-sqlserver
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
