apiVersion: v1
kind: ConfigMap
metadata:
  name: config-prometheus
  namespace: hackaton
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'apps'
        metrics_path: /api/metrics
        static_configs:
          - targets:
            - svc-authapi:8080
            - svc-menuapi:8080
            - svc-orderapi:8080
            - svc-kitchenapi:8080