apiVersion: v1
kind: Service
metadata:
  name: svc-orderservice
  namespace: hackaton
  labels:
    app: orderservice
    component: app
  annotations:
    description: "Worker to Write Data"
spec:
  selector:
    app: orderservice
  ports:
    - port: 9091
      targetPort: 9091
  type: ClusterIP
