apiVersion: v1
kind: Service
metadata:
  name: svc-authapi
  namespace: hackaton
  labels:
    app: authapi
    component: app
  annotations:
    description: "API to receive write operations"
spec:
  selector:
    app: authapi
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
