apiVersion: v1
kind: Service
metadata:
  name: svc-kitchenapi
  namespace: hackaton
  labels:
    app: kitchenapi
    component: app
  annotations:
    description: "API to receive write operations"
spec:
  selector:
    app: kitchenapi
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
