name: Build MenuAPI

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'src/NetArchHackaton.MenuAPI/**'
      - 'src/NetArchHackaton.Shared.Application/**'
      - 'src/NetArchHackaton.Shared.Contracts/**'
      - 'src/NetArchHackaton.Shared.Domain/**'
      - 'src/NetArchHackaton.Shared.Infrastructure/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore and Build
        run: dotnet build src/NetArchHackaton.MenuAPI/NetArchHackaton.MenuAPI.csproj --configuration Release
